### ISSUE TITLE
tox everything

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#100]
The README suggests running tests with python.
Apparently the travis file uses its own matrix.
Ideally everything should be all tox. 

Also, the documentation should guide developers how to run individual tests rapidly without having to run the whole suite across all versions. 

I'm happy to work on this.

**Comment by peterbe** [comment]
Odd. How did you merge this PR? It says it's Closed.

**Comment by willkg** [comment]
This is the issue that pr #105 fixed. So when pr #105 was merged, because it has "fixes #100" in it, it closed this issue, too.

**Comment by peterbe** [comment]
Ha! I thought this was **the PR**. Clicked the link in the notification email too quickly.
