### ISSUE TITLE
How is this different from django-oidc?

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#106]
I.e. https://pypi.python.org/pypi/django-oidc
I think we should document this in the README.

**Comment by willkg** [comment]
The django-oidc library doesn't look well maintained and by having our own library we can handle Mozilla-centric things. I don't think it's worth spelling this out in the README.

**Comment by johngian** [comment]
I added some design principles in README explaining what's the scope of this lib.
