### ISSUE TITLE
Only allow logout on POST

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#126]
We allow logging out simply by GET'ing a URL (`/oidc/logout/`). https://github.com/mozilla/mozilla-django-oidc/blob/04fcbdb1a8697792a7183b99baa0e11beaaa6430/mozilla_django_oidc/views.py#L115

We should probably avoid that. 
E.g. https://stackoverflow.com/a/14587231/205832

**Comment by peterbe** [comment]
Is the likes of mozillians.org ready for switching to POST only? Also, should it require CSRF?
@akatsoulas @johngian

**Comment by johngian** [comment]
Switching mozillians.org will not be a big issue. And yes lets use CSRF.

**Comment by jezdez** [comment]
Ugh, this is kind of a bummer, this should at least be an option. The linked Stackoverflow post is first of all old and second of all about Chrome.

**Comment by peterbe** [comment]
I looked but didn't find any good solid best practice article that pronounces it. I thought it was generally known as best practice and haven't stopped to think about it ever since. 

It's easier to trick logged in users to get them logged out. Which is annoying but not really a security thing. 

I'd be up for an option to override it to *not* require a POST.
