### ISSUE TITLE
We should explain how ID token refreshment and JWT Expiration works

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#129]
I can imagine that it's really confusing to people how the refresh ID token works and how it coincides with JWT Expiration. 

By default, in Auth0, the JWT expiration is 3600 seconds. 
<img width="641" alt="screen shot 2017-06-01 at 9 15 30 am" src="https://cloud.githubusercontent.com/assets/26739/26681344/e41d69ce-46aa-11e7-8dc0-0a4b020e4c89.png">
That means that you have to do an ID token refresher at least every 3600 or it ceases to be valid and the user gets kicked out. (Thanks to our middleware). 

I don't know why Auth0 uses such a low default. Perhaps it's because the concept of constantly refreshing the ID token is optional. And it's set to 3600 just for convenience on the first use. Only with enterprise emails can you "abruptly" lose the right to your email. (Unlike a '@gmail.com` which you won't lose).

Generally, I think the trick is to make sure this number is quite high. In Air Mozilla I think we set it to a week (604800). Meaning, they have to visit the site at least once a week or else they have to sign in again. 

I for one took a long time to understand how this works. Our documentation is a chance to help others. Especially people who want to use the RefreshIDToken middleware.

**Comment by akatsoulas** [comment]
Closing this as stale and not a high priority issue.
