### ISSUE TITLE
The setting SITE_URL is not documented

### ISSUE THREAD

**Issue by kaleissin** [mozilla/mozilla-django-oidc#146]
I'm trying to use mozilla-django-oidc (version 0.2.0) in a fresh django 1.11/python3.5-project, and get 

```
ImproperlyConfigured at /oidc/authenticate/

Setting SITE_URL not found
```

This is not documented anywhere.

**Comment by willkg** [comment]
It's because ReadTheDocs is set up to generate docs for master tip and that just changed.

**Comment by johngian** [comment]
Latest library release doesn't use ``SITE_URL`` config entry.
