### ISSUE TITLE
document logout url

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#147]
The SSO request form asks for a logout url. There's nothing in the docs about logout urls.

I'm a little fuzzy on what this entails.

Should we just document what the logout url that mozilla-django-oidc provides is like we do with the callback url?

Should we have a section that talks about what that logout url does and doesn't do so that users (developers) can do their own thing if they have different requirements?

Are there other things about logout that we should note in the docs?

**Comment by johngian** [comment]
Fixed after #218
