### ISSUE TITLE
push out a new version (0.3.0)

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#148]
This is @peterbe's email:

> Fancy new tag based Travis deployment automation aside, can I humbly please ask for a new release?
> Here's the difference:
> https://github.com/mozilla/mozilla-django-oidc/compare/ebcef60dd54b5d82ee83213b0aff0c47a8b0b14a...master
> 
> I propose a version 0.3.0 (since there are things that might be surprising):

```
0.3.0 (in development)
++++++++++++++++++++++

Backwards-incompatible changes:

* The settings.SITE_URL is no longer used. Instead the absolute URL is
  derived from the request's get_host().
* Only log out by HTTP POST allowed.

Features:

* None.

Bugs:
 
* None
```

> If you're up for it, please consider landing https://github.com/mozilla/mozilla-django-oidc/pull/144 and then we can add a blurb about the fact that the logout view can now only be done by HTTP POST.

**Comment by willkg** [comment]
This will alleviate the issue in #146, too. I can look at fixing that for realz at some point.

**Comment by johngian** [comment]
Done:
https://pypi.python.org/pypi/mozilla-django-oidc/0.3.0
