### ISSUE TITLE
change readthedocs and versioning

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#150]
Issue #146 came about because RTD is set up to build master tip. So any time we merge changes, it updates the docs. Thus the docs can get out of sync with the released version.

This is compounded by two other issues:

1. after we do a release, we don't then update the version to 0.x.y.dev0 or something like that (I do that with my projects) -- if we did this, then the docs would show that they apply to a different version than the released one
2. after we do a release, we don't then update RTD to build docs for that tag as well (I do this with my projects sometimes) -- if we did this, then users would see that the docs they're looking at apply to a different version and can then switch to the version they want to see

The place in RTD to update versions is here:

https://readthedocs.org/projects/mozilla-django-oidc/

But only people who have access to that can do it.

This issue can be fixed entirely by adjusting the release process. I don't know if there's a good way to automate either of them because I do them by hand, but that's probably worth looking into.

I think this is worth fixing process-wise.

How do we want to deal with this?

**Comment by peterbe** [comment]
Pardon my ignorance of RTD, but is it not possible to make builds by tag?
(Then you can have a RTD build for master and one for each tag. "latest" in RTD lingo would point to the latest tag.)
I noticed that http://django-browserid.readthedocs.io/en/latest/ has "latest", "stable" and one version for every github release. But I'm ignorant as to how that was made. 

> How do we want to deal with this?

Keeping it simple and automated :)

**Comment by akatsoulas** [comment]
It looks like that RTD support tags. `latest` can point always to the master branch and the `stable` branch will reflect the tags of each release [0].

We can try this after PR #145 is merged. 
[0] http://docs.readthedocs.io/en/latest/versions.html

**Comment by johngian** [comment]
Hey all! I updated the readthedocs versions to show all tags.

Latest points to master and default readthedocs version is the latest tag.

**Comment by johngian** [comment]
Reopening because i haven't really fixed the automation part that way :\

**Comment by johngian** [comment]
I think its safe to close this now:

RTD builds

* ``master`` version from ``master`` branch
* ``stable`` version from latest tag
* Keeps history of all the tags as different versions
