### ISSUE TITLE
Update legacy references to runtests.py

### ISSUE THREAD

**Issue by claudijd** [mozilla/mozilla-django-oidc#163]
I mentioned to @willkg that I couldn't find runtests.py in the repo.  Sounds like this was left-over from the conversation to using tox and we probably want to update those references.

**Comment by willkg** [comment]
`runtests.py` was removed in PR #105. It's referred to in `Makefile` and that's it now.

**Comment by akatsoulas** [comment]
I opened this [PR](https://github.com/mozilla/mozilla-django-oidc/pull/164) although I am not sure if we should update the commands in the `Makefile` to use `django-admin` or completely remove them since we are using `tox` for the tests.

**Comment by akatsoulas** [comment]
Fixed in #164
