### ISSUE TITLE
Auth backend does not load Django's (model based) permissions

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/mozilla-django-oidc#176]
`OIDCAuthenticationBackend` does not subclass neither implements it's own authorization methods. As a result django (model based) permissions get completely ignored.

I suggest that `OIDCAuthenticationBackend` subclasses `django.contrib.auth.backends.ModelBackend` can get Django's default authorization methods.

While this is not technically a bug, is un-expected behavior thus I suggest that we change it.

Note that [according to the docs](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#handling-authorization-in-custom-backends) Django will fetch permissions for user from all listed `AUTHENTICATION_BACKENDS`. So if `ModelBackend` is included in the list, the user will have model based permissions. Nevertheless I still believe that OIDC backend should provide that functionality itself so we don't have to have ModelBackend enabled as well (which may result in a security risk).

**Comment by johngian** [comment]
Thanks @glogiotatidis for the feedback. I agree that ``OIDCAuthenticationBackend`` should be self contained. That said except of the permissions we might want to ship a template to override the django admin user/pass to allow logins in cases no ``ModelBackend`` is not enabled.

**Comment by peterbe** [comment]
Since https://github.com/mozilla/mozilla-django-oidc/pull/183 is merged now. Can this be closed?

**Comment by johngian** [comment]
Yes, thanks @peterbe
