### ISSUE TITLE
Stop using python-jose

### ISSUE THREAD

**Issue by jezdez** [mozilla/mozilla-django-oidc#180]
Since python-jose is [requiring the use of pycrypto](https://github.com/mpdavis/python-jose/issues/41), which has an [unfixed CVE](https://blog.sqreen.io/stop-using-pycrypto-use-pycryptodome/) it'd be sensible to move away from it.

**Comment by johngian** [comment]
What about using ``pycryptodome`` until we figure out an alternative for ``python-jose``?

**Comment by jezdez** [comment]
@johngian I'm not familiar with the package, maybe @alex ([PyCA](https://github.com/PyCA) member and fellow Mozillian) may know how to proceed?

**Comment by alex** [comment]
pycryptodome resolves that one specific CVE, but I haven't reviewed it any further and so I can't relaly make any claims one way or the other. In either case I'd strongly encourage finding a JOSE library that uses pyca/cryptography :-) (or porting python-jose to pyca/cryptography of course) -- I don't know offhand what exists in that space.

pycryptodome is still built on a lot of bespoke algorithm implementations and inherits a lot of the dangerous API designs that PyCrypto has.

**Comment by alex** [comment]
Quick follow up: certbot (the Let's Encrypt python client) has a JOSE implementation built on pyca/cryptography, I know Mozilla has several folks who are contributors to it, so turning this into a standaone library might be a good way to kill two birds with one stone :-)

**Comment by johngian** [comment]
Here is the documentation for the API call that we need to use:
http://letsencrypt.readthedocs.io/projects/acme/en/latest/api/jose/jws.html#acme.jose.jws.Signature.verify

I will dive more into this. Thanks @alex

**Comment by alex** [comment]
Sure thing -- fair warning, I don't think the certbot team considers that API to be stable. /cc @erikrose to confirm

Please let me know if there's any other way I can help.

**Comment by erikrose** [comment]
I asked around. Since Kuba left the LE project, acme's API has been pretty stable; we also have other people using the lib, so we've been very cautious about breaking changes. acme v2 is coming, but I'm not sure of the timeline on that.

**Comment by erikrose** [comment]
Also, bmw over at LE is also interested in having it broken out as a separate package, so you can expect good collaboration over there.

**Comment by jezdez** [comment]
FYI, I've coordinated with LE people and will do the separate release of the acme.jose package. Anyone have a good name for the package?

**Comment by tiran** [comment]
There are a couple of JOSE libraries for Python. https://github.com/latchset/jwcrypto is written by @simo5 and me. We are using it in a couple of applications related to FreeIPA / RHEL identity management.

https://github.com/jpadilla/pyjwt is another mature library but I haven't used it yet.

**Comment by jezdez** [comment]
@tiran Hey there! I was wondering about that while researching alternatives but lacked the context. Do you recommend to convince ACME to adopt it? Or just for this use case?

**Comment by jezdez** [comment]
Since I had already started the port, I've just finished it and released it on [PyPI as josepy](https://pypi.python.org/pypi/josepy).

[code](https://github.com/jezdez/josepy), [docs](https://josepy.readthedocs.io/en/latest/), [ci](https://travis-ci.org/jezdez/josepy).

I realize there is major overlap with jwcrypto (which I like more after looking at its API), but I feel going with the letsencrypt provided library is currently closer to our needs. @johngian Do you have someone in mind at Moz we can ping about reviewing the change in JOSE implementation from a security perspective?

**Comment by simo5** [comment]
@jezdez jose implementations already were found multiple times to have sistemic widespread security issues, I would rather not recommend adding yet another implementation and instead work together with others on an existing one so that the maintenance burden is shared rather than spread thin over multiple code bases.
Use the implementation you prefer, but use an existing, maintained one please.

**Comment by johngian** [comment]
@jezdez regardin security reviews:

In the past @claudijd had done some auditing for ``mozilla-django-oidc``.

**Comment by jezdez** [comment]
@simo5 FWIW, the implementation that I released has been extracted from the [acme.jose](https://github.com/certbot/certbot/tree/232f5a92d193b1b4a955d0d5f2d1ea639215331d/acme/acme/jose) package by the letsencrypt folks and is not a new one. Why they chose to write their own I'm not sure (maybe @bmw knows?) but while researching a library I've found no clear statement that jwcrypto has a higher chance of long term maintenance. I'm happy to be wrong though, since I totally agree that there should be only one library based on cryptography that implements JOSE. It makes sense to me that having fewer libraries implementing JOSE reduces the chance of having an unfixed vulnerability again.

@alex Have you considered blessing one of the existing JOSE libraries and move it into the PyCA organization, making it the de facto standard implementation?

@bmw @erikrose Have you considered *dropping* your JOSE implementation in favor of one that is equally or better maintained than `acme.jose`?

@tiran @simo5 Do you consider jwcrypto to be secure in terms of long term maintenance?

**Comment by alex** [comment]
We've contemplated it before, at a very high level, but never done any work towards it or thought about the details.

**Comment by bmw** [comment]
> Have you considered dropping your JOSE implementation in favor of one that is equally or better maintained than acme.jose?

We haven't really thought about it as our `acme.jose` module was written a while ago and requires very little maintenance for usage of it. While switching to something new wouldn't be a high priority for us, we'd happily change to a well maintained third party library in the long term if it worked well for us.

**Comment by bmw** [comment]
Whoops. Just saw this:

> Why they chose to write their own I'm not sure (maybe @bmw knows?) 

I don't know for sure. The developers who made that decision are unfortunately no longer involved in the project. I'll ask around (and if I learn anything definitive I'll post back), but I suspect the issue was lack of available third party libraries at the time. We started working on our JOSE implementation in 2014, before many of the other libraries mentioned in this thread were uploaded to PyPI.
