### ISSUE TITLE
Improvements to verify the token through the jwks

### ISSUE THREAD

**Issue by GermanoGuerrini** [mozilla/mozilla-django-oidc#187]
Currently, the only way to verify a token using the RS256 algorithm is to hard-code the signing key in a settings parameter.

I'm not really an expert here, but I have seen other implementations (not in Python) that take advantage of the (possible) JWKS endpoint of the identity provider. Documentation can be found here: https://auth0.com/docs/jwks.

I have a local branch of mozilla-django-oidc where it's working. Basically I verify whether a signing key or a JWKS endpoint is set, and in the latter case I try to match a key with the key id retrieved from the token and pass it on to jose to run the verification in place of the hard-coded one.
It works like a charm, except the fact that I have to decode the token first and to do that I have to use a private python-jose method (`jose.jws._load`) which I think is blatantly taken from pyjwt.

I have seen that a new branch has been made that uses the new josepy package, and it seems that decoding the token using that is no longer a private affair.

Can a modification like that be of any interest? It seems strange to me that I'm the only one needing  such a workflow.

**Comment by Bartvds** [comment]
Any word on this? We've got to use Gigya as IDP and they also use RS256 with JWKS.

**Comment by GermanoGuerrini** [comment]
@Bartvds There's a pull request https://github.com/mozilla/mozilla-django-oidc/pull/196 if you want to give it try.

**Comment by johngian** [comment]
Closing this one after #229
