### ISSUE TITLE
Add automation to do integration testing

### ISSUE THREAD

**Issue by johngian** [mozilla/mozilla-django-oidc#191]
At the moment our testing infrastructure relies only in unit tests. We should have a way to actually test the authentication backend against an django project.

I suggest the following:

* Use a self hosted oidc provider
  * Possible candidate: https://github.com/juanifioren/django-oidc-provider
* Install mozilla-django-oidc to a test app (that supports multiple python versions)
* Orchestrate integration testing using a headless browser

**Comment by willkg** [comment]
This is related to issue #63. Solving one probably helps solve the other.

**Comment by johngian** [comment]
Fixed after #205 

This allows devs to run e2e tests locally and adds circleci support.
