### ISSUE TITLE
can i customize the configuration of 'redirect_uri' ?

### ISSUE THREAD

**Issue by zhangyile** [mozilla/mozilla-django-oidc#193]
Because I forwarded the request through nginx, I need to customize ‘redirect_uri’
#### mozilla_django_oidc/views.py

    125         params = {
    126             'response_type': 'code',
    127             'scope': import_from_settings('OIDC_RP_SCOPES', 'openid email'),
    128             'client_id': self.OIDC_RP_CLIENT_ID,
    129             'redirect_uri': absolutify(
    130                 request,
    131                 reverse('oidc_authentication_callback')
    132             ),
    133             'state': state,
    134         }

**Comment by johngian** [comment]
The redirect URI is configurable using this config entry:

http://mozilla-django-oidc.readthedocs.io/en/stable/settings.html#OIDC_AUTHENTICATION_CALLBACK_URL

You can define a URL to your project ``urls.py`` and set this config value to that URL pattern name.
