### ISSUE TITLE
Change variable name `mozilla_django_oidc.middleware.RefreshIDToken` to something else

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/mozilla-django-oidc#200]
Kind of a nitpick, however, `RefreshIDToken` is a confusing name because refresh tokens are a very specific thing: non-expiring access tokens.
In this case, this is the opposite, its a token that expires and needs periodic refresh.

**Comment by willkg** [comment]
What's a better name for this?

**Comment by gdestuynder** [comment]
I usually call is `SessionRefresh` though there may be better/more fitting names.

**Comment by willkg** [comment]
I'll do a PR now.

**Comment by willkg** [comment]
Django 2.0 released recently and mozilla-django-oidc tests are failing. Once #203 lands, I can work on this.

**Comment by peterbe** [comment]
@willkg Gentle poke here that https://github.com/mozilla/mozilla-django-oidc/pull/203 is now merged.

**Comment by willkg** [comment]
Oo--I'll try to do this by the end of the month. Thank you for the ping!
