### ISSUE TITLE
OIDCAuthenticationCallbackView.success_url ignores session value

### ISSUE THREAD

**Issue by tpazderka** [mozilla/mozilla-django-oidc#224]
Because `OIDCAuthenticationCallbackView.success_url` is called only after `auth.login`, the session is already cycled and user is redirected according to settings instead of URL stored session.

**Comment by tpazderka** [comment]
Nevermind, the `OIDCAuthenticationCallbackView` actually rewrites any saved values with its own from request...

Maybe consider not replacing values already in session?

**Comment by tpazderka** [comment]
My original idea was to have the link with login URL without the `next` value and save the `oidc_login_next` to session myself in the view logic. This of course gets overwritten in the `OIDCAuthenticationCallbackView`.

This seemed counterintuitive to me so I raised this issue.

My idea was to not overwrite the value in session if there is already something. This would allow the implementator to construct the `success_url` in the view logic and keep the login URL "clean".

**Comment by johngian** [comment]
Cool, thanks for the clarification, now it makes sense. I was missing the part that you manually changed the ``oidc_login_next`` in your view logic.

**Comment by tpazderka** [comment]
Yeah, sorry for the confusion :) The issue was evolving as I was experimenting with something...

**Comment by akatsoulas** [comment]
For more context see #232
