### ISSUE TITLE
Is it possible to use mozilla-django-oidc together with Django REST framework?

### ISSUE THREAD

**Issue by NorthCat** [mozilla/mozilla-django-oidc#227]
Is it possible to use mozilla-django-oidc together with Django REST framework?
If so, please give detailed instructions.

**Comment by anlutro** [comment]
I'm pretty sure this is not currently possible, but it would be a great addition.

Here's the DRF docs on how to implement an authentication backend: http://www.django-rest-framework.org/api-guide/authentication/#custom-authentication

Basically you just need an `authenticate(self, request)` method which returns the user model + arbitrary(?) authentication information based on the request (by looking at tokens in headers or whatever).

I think this just means extracting [this block of code](https://github.com/mozilla/mozilla-django-oidc/blob/c6d9906aa24a549ee9313023e638b4e1e6bda64a/mozilla_django_oidc/auth.py#L197-L228) into a standalone method/function, which can then be re-used in the DRF authentication backend.

**Comment by johngian** [comment]
Fixed after #231
