### ISSUE TITLE
Refactor of class constructors (in support of multi-site applications)

### ISSUE THREAD

**Issue by cobusc** [mozilla/mozilla-django-oidc#235]
I am working on a project where we want to support multiple sites from a single Django instance. The `sites` framework is used. In order to support multiple OIDC clients, I had to subclass most views and override methods to set the `CLIENT_ID` and `CLIENT_SECRET` based on the applicable site.

For some views (https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/views.py#L122-L138) it was simple. Redacted example:
```
class CustomAuthenticationRequestView(OIDCAuthenticationRequestView):
    def get(self, request):
        site = get_current_site(request)
        self.OIDC_RP_CLIENT_ID = site.oidcsettings.oidc_rp_client_id
        self.OIDC_RP_SCOPES = site.oidcsettings.oidc_rp_scopes
        return super().get(request)
```

For others (https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/middleware.py#L83-L139) I had to copy and modify the code, which is not ideal.

This brings me to my suggestion: It looks like it would make sense to perform all calls to`import_from_settings` in the constructors of classes, setting the appropriate instance variables for use in the class methods. This would then make it trivial for anyone who wants to tweak the behaviour based on requests, for instance, as shown in my first link.

Your thoughts?

At the very least I feel that the following function should be changed, so that the CLIENT_ID, CLIENT_SECRET and SCOPES can be easily overriden: https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/middleware.py#L83 

Please let me know what you think of the suggestion and whether it is something you would be able to do or whether you would like me to jump in and help.

**Comment by johngian** [comment]
Closing this one after #308 is already in production. You can now override `get_settings` per class to add custom settings.

Thanks @cobusc for the feedback.
