### ISSUE TITLE
How to access the role and permission of logged in user 

### ISSUE THREAD

**Issue by rackmuthu** [mozilla/mozilla-django-oidc#243]
I have keycloak (SSO provider). here i am have idea about how to access the role and permission of the logged in user

**Comment by johngian** [comment]
I am not familiar with keycloak specifically but it should return claims in this format:
http://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse

There you can either use the default strategy which matches users based on email or override these 2 methods for custom functionality:

https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/auth.py#L68
https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/auth.py#L75
