### ISSUE TITLE
Login fails after authorizing user 

### ISSUE THREAD

**Issue by Algogator** [mozilla/mozilla-django-oidc#244]
> [06/Jun/2018 17:13:03] "GET /oidc/authenticate/ HTTP/1.1" 302 0
[06/Jun/2018 17:13:09] "GET /oidc/callback/?state=lY57giXxu5WWd4s1OqDYHXlOG4pUhEZm&code=3925eb48-e352-4ba8-a165-aa91fe709662_9dK5ps3XQM_HGTP1J4LA7IX_rViZbVGT HTTP/1.1" 302 0
[06/Jun/2018 17:13:10] "GET /oidc/callback/ HTTP/1.1" 302 0

The site is redirected to the login failure url after authorizing the user

`

**Comment by vitorcarareto** [comment]
I'm exactly with the same problem...

On views.py, line 81, it enters this condition:
```
            if 'oidc_state' not in request.session:
                return self.login_failure()
```

What can I do to get the session with 'oidc_state', so that it doesn't fail?

**Comment by Algogator** [comment]
I think I was missing the session middleware

**Comment by vitorcarareto** [comment]
Did you solve the problem?
Could you please post your middlewares list, so that I can see the order you used?

**Comment by bpereto** [comment]
I'm expecting the same issue as described by @vitorcarareto 
https://github.com/mozilla/mozilla-django-oidc/issues/244#issuecomment-406252387

My Testsetup:
* Session Middleware is included.
* OIDC_VERIFY_SSL=False
* localhost:8000 is my oidc provider (django-oidc-provider)
* localhost:9000 is the client (mozilla-django-oidc)

**Comment by bpereto** [comment]
Ok, got it.
django login clears the session of the same domain. Since its localhost, it clears also the session storage of the "client" (mozilla-django-oidc).

it works fine when running separate:
* 127.0.0.1:8000
* 127.1.1.1:9000

**Comment by Flor1an-dev** [comment]
@bpereto A bit late but you should define the `SESSION_COOKIE_NAME` differently in each app (client / provider). Django will then use two different cookie for each application and won't overwrite each other. The same is true for the `LANGUAGE_COOKIE_NAME` and the `CSRF_COOKIE_NAME`.

Can we close the issue?

**Comment by johngian** [comment]
Thanks @Flor1an-dev for the clarification.

**Comment by paulpavlishcoupa** [comment]
I had the same issue that @bpereto had. 

Here is how I solved the problem
1. Please make sure you clear your cookies to reset your session for localhost.
2. Change domain (use mycomputer.local instead of localhost). You will have to update your `ALLOWED_HOSTS` if it isn't ['*'] and you need to update your start script allow all ingress. For example
`python manage.py runserver 0.0.0.0 9000`
3. Changing SESSION_COOKIE_NAME is also a good idea as well.

**Comment by maszaa** [comment]
I'm occasionally facing this issue as well. Session Middleware is enabled. OIDC_VERIFY_SSL is True. I'm using DB stored sessions.

OIDC provider and client are in different domains (provider is 3rd party).

Client users shouldn't be using any sub domains. If they are it's a one sub domain which is redirected to the "main" domain. That sub domain request doesn't reach Django.

What are possible reasons for this?
The session has expired and new one has been created and therefore `oidc_state` is missing in the session?
For some reason 'oidc_state' saving to the session object in DB fails and when the callback view attempts to read it, it's not there?

**Comment by gummibearz** [comment]
we had defined CustomOIDCAuthenticationCallbackView so we had to update the following oidc_state check

with the following
https://github.com/mozilla/mozilla-django-oidc/blob/2a7a1b23175316db22b9f7b6a850819fdb86cc58/mozilla_django_oidc/views.py#L72
