### ISSUE TITLE
Drop conditional cryptography version

### ISSUE THREAD

**Issue by ziima** [mozilla/mozilla-django-oidc#245]
`mozilla-django-oidc` forces `cryptography<1.9` to be used under python 2.7, which does not make any sense. Cryptography still supports the python 2.7 and there is no reason to keep it back.

**Comment by johngian** [comment]
This was only happening for ``2.7 < python <= 3.3``.  That said we dropped support for these python versions so it's safe to add cryptography directly to requirements.

Fixed here:
https://github.com/mozilla/mozilla-django-oidc/pull/250
