### ISSUE TITLE
Unclear how to redirect back to desired URL after completing login.

### ISSUE THREAD

**Issue by jschwartzentruber** [mozilla/mozilla-django-oidc#276]
When I request /app/index on our domain, I am redirected to auth0, authentication completes, and I'm redirected back to our domain, but at / instead of /app/index.

I do have `LOGIN_REDIRECT_URL = '/'` in settings.py, but I understood that to be where an explicit login request would go, I thought an implicit login redirect would continue at the original url. Is that wrong?

I'm guessing this is a mis-configuration, so this is just a help/documentation request.

**Comment by chrisbrantley** [comment]
I struggled with this as well. Is your site using HTTPS?

There are a couple things that need to happen for the redirect to work:
1. the redirect URL needs to be in the `next` query param in the initial redirect to the login view. I believe this happens automatically if you're redirected to login but you'll need to do it yourself if you're creating a login link.
2. The redirect URL itself needs to be on the SAME DOMAIN as your main site.
3. The redirect URL needs to use HTTPS

**Comment by jschwartzentruber** [comment]
Thanks!  1. was the issue.

We have a view adding a level of indirection between OIDC and default Django auth depending on settings, and that was losing the `next` parameter. The commit is https://github.com/MozillaSecurity/FuzzManager/commit/2ccb436a25f474d97786d27c3bcc466d502943aa.
