### ISSUE TITLE
url oidc_logout - should get-request work?

### ISSUE THREAD

**Issue by AndyNor** [mozilla/mozilla-django-oidc#282]
In urls.py there is a url for logging out. I could not find the documentation for it or any examples using it except for the mention of OIDC_OP_LOGOUT_URL_METHOD under https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#log-user-out-of-the-openid-connect-provider.

url(r'^logout/$', views.OIDCLogoutView.as_view(), name='oidc_logout') points to OIDCLogoutView in views.py. It defines http_method_names = ['get', 'post'], but the part using OIDC_OP_LOGOUT_URL_METHOD is used only in the def post(self, request): method. 

Simply changing "post" to "get" fixes logout of my identity provider.
Is the "get" verb forgotten here, or am I using this the wrong way?

**Comment by Pike** [comment]
Just stumbling over this myself. The POST-requirement was added in #126, with mixed feelings.

I'm currently just using the standard logout view from django, which may or may not be a bad idea.

**Comment by phamj88** [comment]
is there an example on how to setup the post request for logout?

**Comment by johngian** [comment]
Hey @phamj88, here is an example from `support.mozilla.org`:

https://github.com/mozilla/kitsune/blob/35471a1b4ca56c816408437f52c508dda434fa0e/kitsune/users/jinja2/users/profile.html#L192

**Comment by johngian** [comment]
Closing this one after #314
