### ISSUE TITLE
setup with okta

### ISSUE THREAD

**Issue by phamj88** [mozilla/mozilla-django-oidc#289]
Hi All,

I am getting an exception whenever I authenticate and get redirected back to /oidc/callback:
```
django.core.exceptions.SuspiciousOperation: The provider algorithm 'RS256' does not match the client's OIDC_RP_SIGN_ALGO.
```
Reading Okta documentation it says it is default 'HS256' so I dont know why it is saying RS256.
But its not obvious on the Okta app, has no settings for what time of signing algorithm it uses.
https://developer.okta.com/docs/api/resources/oidc#token-authentication-methods

On my Okta app I can see OIDC access token is granted
My setup is exactly like everything default on the installation guide.

Okta app:
Login redirect URIs: http://localhost:8000/oidc/callback/
Initiate login URI: http://localhost:8000/oidc/callback/

settings.py vars for endpoints:
```
 OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://myaccount.oktapreview.com/oauth2/v1/authorize'
 OIDC_OP_TOKEN_ENDPOINT = 'https://myaccount.oktapreview.com/oauth2/v1/token'
 OIDC_OP_USER_ENDPOINT = 'https://myaccount.oktapreview.com/oauth2/v1/userinfo'
```

Anyone familiar with Okta or run into this issue yet?

Thanks!

**Comment by phamj88** [comment]
duh.
Changed OIDC_RP_SIGN_ALGO to RS256.
I think im getting further.
Is OIDC_OP_JWKS_ENDPOINT the /keys uri?
https://developer.okta.com/docs/api/resources/oidc#keys
 Now I am getting:
```
failed to get or create user: Claims verification failed
```

**Comment by RubenGarcia** [comment]
I'm getting the same issue "failed to get or create user: Claims verification failed". phamj88, can you point to the solution?
