### ISSUE TITLE
Verify email breaks authentication (regression 1.2.0)

### ISSUE THREAD

**Issue by ziima** [mozilla/mozilla-django-oidc#290]
Change from #285 breaks authentication in some cases. The check is unconditional, so in case `OIDC_CREATE_USER` is set to `False` and `email` is not requested, the authentication starts failing after migration to version 1.2.0.

**Comment by johngian** [comment]
Hey @ziima thanks for the feedback. How are you requesting the scope from your OP. Are you defining it in ``settings.OIDC_RP_SCOPES``?

**Comment by ziima** [comment]
Yes, we set `OIDC_RP_SCOPES = 'openid'` since that's the only scope we use.

**Comment by johngian** [comment]
Hi! This should be fixed after #293
