### ISSUE TITLE
mozilla-django-oidc, Session flushed between authorize and callback

### ISSUE THREAD

**Issue by ZedObaia** [mozilla/mozilla-django-oidc#291]
I'm trying to set up a client to authenticate using a provider that I built.
I followed the quick start in the docs and here's the relates **settings**:
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'mozilla_django_oidc',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
```
```
AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)   
```

```
OIDC_OP_JWKS_ENDPOINT = "http://127.0.0.1:8000/openid/jwks"
OIDC_RP_CLIENT_ID = 'id'
OIDC_RP_CLIENT_SECRET = 'secret'

OIDC_OP_AUTHORIZATION_ENDPOINT = "http://127.0.0.1:8000/openid/authorize"
OIDC_OP_TOKEN_ENDPOINT = "http://127.0.0.1:8000/openid/token"
OIDC_OP_USER_ENDPOINT = "http://127.0.0.1:8000/openid/userinfo"

OIDC_CREATE_USER = True
OIDC_RP_SCOPES = "openid profile email"
```
and in the **templates**
```
    {% if request.user.is_authenticated %}
      <p>Current user: {{ request.user.email }}</p>
    {% else %}
      <a href="{% url 'oidc_authentication_init' %}">Login</a>
    {% endif %}
```
I get redirected to the provider when i click login, and I get a callback with the authorization code, but the client never post data to the token endpoint.

**Comment by ZedObaia** [comment]
I found out the problem, the session gets flushed between `authorize` and `callback`. so the variables such as `state` that are saved in session are no longer verified, thus it fails to call the token endpoint.

Something strange happens as well, when redirected to the provider it forces a logout from the provider's website.

Still trying to figure out why that happens and how to overcome this issue

**Comment by thys-unomena** [comment]
Hi @ZedObaia 

Did you get this resolved?
I'm seeing the same behaviour ...

**Comment by ZedObaia** [comment]
Hey @thys-unomena 
Turned out the issue was not related to mozilla-django-oidc.
I was using another package called django-oidc-provider to build the open-id provider.
Here's the [issue](https://github.com/juanifioren/django-oidc-provider/issues/314) and it's solve.

**Comment by severinkl** [comment]
> Hi @ZedObaia
> 
> Did you get this resolved? I'm seeing the same behaviour ...

Did you get this resolved?
