### ISSUE TITLE
getting token id to logout

### ISSUE THREAD

**Issue by phamj88** [mozilla/mozilla-django-oidc#292]
logout requires a token id, how do you get the token?
Looking at the documents looks like i should be able to get it from sessions if `OIDC_STORE_ID_TOKEN = True`

But doesn't seem to work.
Logout view:
```
 def logout_page(request, *args, **kwargs):
    ...
     pprint(request.session.get('oidc_id_token'))      # None                                                                                                                                                                                   
     pprint(request.session.get('id_token'))   # None
     return HttpResponseRedirect(logout_url)

```

**Comment by benjaminaudet** [comment]
Up

**Comment by drwonky** [comment]
To logout you need the logout endpoint, /oidc/logout/ and you need the CSRF token, that's all.

**Comment by akatsoulas** [comment]
I am closing this per the last comment. Please re-open if the answer does not addresses the issue.
