### ISSUE TITLE
Readthedocs integration no longer working

### ISSUE THREAD

**Issue by gene1wood** [mozilla/mozilla-django-oidc#296]
With [GitHub services being turned off yesterday](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) the Readthedocs integration has stopped working and changes to documentation will no longer result in updated to the readthedocs site for this project. Please create [a Readthedocs GitHub webhook](https://docs.readthedocs.io/en/latest/webhooks.html#webhook-creation) to re-enable this functionality.

**Comment by johngian** [comment]
Added the webhook and triggered builds for the skipped versions. Thanks @gene1wood
