### ISSUE TITLE
add support for OpenID Connect Session Management 1.0

### ISSUE THREAD

**Issue by benkonrath** [mozilla/mozilla-django-oidc#299]
I've implemented OpenID Connect Session Management 1.0 on top of mozilla-django-oidc for a project that I'm working on and I'm wondering if you're interested in having support for this (draft) standard included in mozilla-django-oidc itself.
https://openid.net/specs/openid-connect-session-1_0.html

Basics of this standard involve loading a hidden iframe from the RP and the OP which allows the RP to check the authentication status on the OP with JavaScript (in the iframe) and re-authenticate if needed. I know that there's already a middleware that refreshes the authentication status periodically but the session management standard is more efficient because it doesn't need network requests to the OP for status checks. This means we can check more frequently e.g. every 3 seconds. In the project I mentioned, we have both the session management iframe and the refresh middeware enabled so that malicious users can be deactivated even if JavaScript is disabled in their browser.

I'm curious to hear what people think about including this in mozilla-django-oidc before I spend the time making PR for this. Thanks.

**Comment by johngian** [comment]
Hey @benkonrath. That would be very interesting. As long as it follows the spec and is optional (maybe under `contrib/`) so people can configure it, I will be happy to review and merge.

**Comment by benkonrath** [comment]
I recently finished working on the project that I mentioned so I don't think I'll be able to make a PR anytime soon. There's a small chance I could get back to this in the next couple of months. If I do, I'll just open a new PR directly. But for now, I'm closing this issue because I don't have specific plans to make this contribution in the near future.
