### ISSUE TITLE
504 errors on network with proxy

### ISSUE THREAD

**Issue by minrock** [mozilla/mozilla-django-oidc#307]
Hi everyone, thank you for your great work!

I'm using your library on an enterprise environment which requires me to connect to a VPN and route everything through a proxy for internet, but in my case my server is inside intranet and I should not use environment HTTP/HTTPS proxy to route my request to the OIDC server so I need to send my requests as `request.post(self.OIDC_OP_<whatever>, data=data,..., proxy={'HTTP': None, 'HTTPS': None})` so that way it will not take in consideration the proxy for the request but there is no way to inject proxies to all requests by the requests package, so not sure if you can do it but it would be nice to have a settings option to override all proxy requests if needed.

If I do not set proxies as None I get this error:
`requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for URL: http://my_server_url/openid/token/`

Thanks for your responses.

Best regards.

**Comment by johngian** [comment]
Hey @minrock i am not sure if its in the scope of the library. For your issue, have you tried this:
http://docs.python-requests.org/en/master/user/advanced/#proxies ?

You can setup env vars for python requests to use proxies, that said i haven't tried it.

**Comment by minrock** [comment]
Hi @johngian.
Yes I was looking at that documentation but without lucky 'cause I need to set the environment proxies for internet related stuff in my containers, but for internal requests, I need to bypass that proxy.

However, I found something interesting that may help me with my problem, this is not in the documentation but found on the code to use NO_PROXY environment variable. I'll make some tests and check if works.

I'm leaving the thread with the inclusion of the requirement to use NO_PROXY inside request if someone else needs it.
https://github.com/kennethreitz/requests/issues/2817

Bye.
