### ISSUE TITLE
JWT Nonce verification failed

### ISSUE THREAD

**Issue by cfra** [mozilla/mozilla-django-oidc#312]
In my application, I am seeing a `SuspiciousOperation: JWT Nonce verification failed.` in the logs from time to time.

I am not sure what the reason for this is.

The identity provider seems to always return the nonce correctly.

One guess of mine is that these are maybe flaky clients where the first request for the callback page makes it through to the server, but the response which sets up the authenticated session doesn't make it back to the client. When the user then reloads the callback page, the nonce has already been stripped from the session and so verification fails.

Is this a valid and likely assumption? Or is there a more plausible explanation?

Looking at the control flow, it seems like login will fail for users which trigger this path.

There is however also an option `OIDC_USE_NONCE` which would permit to turn off this validation completely.

I couldn't find any documentation about the security implications of that setting. Is there any recommendation under which circumstances it might be acceptable not to enable this feature?

**Comment by johngian** [comment]
The reason OIDC uses nonce is to protect you from replay attacks. The idea is that the application generates the nonce and sends it to the OIDC provider on authentication request. Then the provider includes this nonce to the callback so you can correlate the authentication response to the initial request.

What we've noticed in some apps is that we get the same error when a user initiates the authentication from tab A and opens the callback to tab B on a different session (eg, different browser or container). Session in B doesn't have the nonce value and then django throws this error.

**Comment by johngian** [comment]
Also yes, your assumption also sounds plausible.

**Comment by cfra** [comment]
I have to admit I am not too familiar with OIDC, but from my understanding of OAuth 2.0, when control is passed back from the authentication provider to our callback, our application is passed an authorization code which it will exchange for an access token.

That exchange is only possible once, if there is another attempt to exchange the same authorization code for an access token, all access tokens previously generated for this access code will be invalidated.

Doesn't this already protect against replay attacks?
What is an attack scenario where the nonce provides better security?

**Comment by johngian** [comment]
An example from the top of my head is:

* User A initiates authentication flow
* User A gets redirected to OP
* Malicious user B sniffs the `id_token` from the network
* Replays the authentication flow to the RP before user A and authenticates successfully

With `nonce` associated with user A session, user B cannot authenticate to the RP because `nonce` cannot be validated.

**Comment by florian-hartmann** [comment]
> What we've noticed in some apps is that we get the same error when a user initiates the authentication from tab A and opens the callback to tab B on a different session (eg, different browser or container). Session in B doesn't have the nonce value and then django throws this error.

I do get the same errors with the situation described above. I also think it is related to issue #303 !

- Tab A wants to authenticate, sets a nonce and state in the session, is being redirected to the OAuth provider.
- Tab B is opened, sets overwrites nonce and state in the session, is redirected to the OAuth provider.
- Tab A now authenticates at the OAuth provider and is being redirected back to the callback.
- As nonce/state have been changed by tab B, the nonce and state in the redirection don't match anymore!
- Tab A gets a shown an error.

One idea to circumvent this problem would be store nonce+state in a list in the session. If user is being redirected back to the callback, it needs to check for one valid combination in the list.

**Comment by Flor1an-dev** [comment]
I've created a merge request which should fix this issue: https://github.com/mozilla/mozilla-django-oidc/pull/345

**Comment by akatsoulas** [comment]
This issue was fixed through #345 and #358
