### ISSUE TITLE
how can I show the keycloak user ID 

### ISSUE THREAD

**Issue by insaneda** [mozilla/mozilla-django-oidc#313]
from the doc, i can print user email but why can't I access the other credentials like **username, user id** from keycloak server?
According to keycloak server, **user.sub** should've print user ID but in vain it doesn't work. How can I solve this?
```
<html>
  <body>
    {% if user.is_authenticated %}
      <p>Current user: {{ user.email }}</p>
     <p>Current user id: {{  user.sub  }}</p> doesn't print anything
    {% else %}
      <a href="{% url 'oidc_authentication_init' %}">Login</a>
    {% endif %}
  </body>
</html>
```
Do I have to change any other things to access the use id?

**Comment by johngian** [comment]
By default `mozilla-django-oidc` only stores username/email. In case you want to add store more information from the user claims you should extend your `User` model and override the authentication backend as described here:

https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#changing-how-django-users-are-created

**Comment by johngian** [comment]
Since we are planning to keep the library as minimal as possible i will go ahead and close this issue.

@insaneda Let me know if you need further information on how to store claims to your User.

**Comment by insaneda** [comment]
@johngian i'm kinda new to django. Where should I write that override code? should I write that on **settings.py** or **models.py**?  And I didn't get this line, can you please explain to me this  `use the Python dotted path to that class in the settings.AUTHENTICATION_BACKENDS instead of mozilla_django_oidc.auth.OIDCAuthenticationBackend.`

**Comment by insaneda** [comment]
> Since we are planning to keep the library as minimal as possible i will go ahead and close this issue.
> 
> @insaneda Let me know if you need further information on how to store claims to your User.

@johngian i'm kinda new to django. Where should I write that override code? should I write that on settings.py or models.py? And I didn't get this line, can you please explain to me this use the Python dotted path to that class in the settings.AUTHENTICATION_BACKENDS instead of mozilla_django_oidc.auth.OIDCAuthenticationBackend.

**Comment by akatsoulas** [comment]
Hi @insaneda,

The Django documentation [0] has a couple of examples on how you can extend the user model and add more information to it. After that you need a way to store that new information in your user model. That's where the authentication backend comes in. By default the library does not store the information that you need, so you will need to follow the documentation [1] and store/update your `sub` attribute (and any other additional information you might need) when a new user is created/updated.

[0] https://docs.djangoproject.com/en/2.2/topics/auth/customizing/
[1] https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#changing-how-django-users-are-created

**Comment by insaneda** [comment]
Thanks @insaneda . I'll work on that.
 But I've got a new problem. If a user has email, then user authentication is not working like `claims verification failed`. I tried to override verifyclaims method but that needs claims and for claims I need id_token, but that id_token never created if a user has no email address.
What should I override so, if a user has no email still it will be authenticated?
