### ISSUE TITLE
Overriding 'verify_claims' method problem

### ISSUE THREAD

**Issue by insaneda** [mozilla/mozilla-django-oidc#315]
I'm trying to override the `verify_claims` method but somehow it's not working or maybe my process is wrong. This is how I'm trying to override this method:

**models.py**
```
from mozilla_django_oidc.auth import OIDCAuthenticationBackend

class MyOIDCAB(OIDCAuthenticationBackend):
    def verify_claims(self, claims):
         print('working')
         return True
```
**views.py:**
```
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from myapp.models import MyOIDCAB

def loginpage(request):
    return render(request, 'index.html')

@login_required
def private(request):
       return render(request, 'private.html') 
  
```
**templates/index.html**
```
<html>
  <body>
        <a href="{% url 'oidc_authentication_init'%}">Login</a> 
  </body>
</html>
```
this template view is not overriden, how can I override this correctly? Do I've to change something on **settings.py** or **urls.py**?

**Comment by akatsoulas** [comment]
Have you added your custom backend to your settings as described here?
https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#add-settings-to-settings-py

**Comment by insaneda** [comment]
no, i've used the backend the was mentioned in the docs:

```
AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    # ...
)
```
this one

**Comment by akatsoulas** [comment]
Since you are overriding the backend with a custom one, you need to add it to your settings too.
You can read more about it here
https://docs.djangoproject.com/en/2.2/topics/auth/customizing/

**Comment by akatsoulas** [comment]
I am closing this issue as it's not related to the library. Thank you for filing the issue.
