### ISSUE TITLE
Client error on keycloak token endpoint

### ISSUE THREAD

**Issue by SpaceWhite** [mozilla/mozilla-django-oidc#317]
Hi

I tried to integrate django with keycloak openid by using this library. Unfortunately I got this message 
```
400 Client Error: Bad Request for url: http://KEYCLOAK-IP/auth/realms/myrealm/protocol/openid-connect/token
```

Here is my sample settings in my django application
```
OIDC_RP_SIGN_ALGO = 'RS256'

OIDC_OP_JWKS_ENDPOINT = 'http://KEYCLOAK-IP/auth/realms/myrealm/protocol/openid-connect/certs'

OIDC_RP_CLIENT_ID = 'webapp'
OIDC_RP_CLIENT_SECRET = '29357c72-ed21-4a4c-a882-58194b63cb1f'


OIDC_OP_AUTHORIZATION_ENDPOINT = 'http://KEYCLOAK-IP/auth/realms/myrealm/protocol/openid-connect/auth'

OIDC_OP_TOKEN_ENDPOINT = 'http://KEYCLOAK-IP/auth/realms/myrealm/protocol/openid-connect/token'

OIDC_OP_USER_ENDPOINT = 'http://KEYCLOAK-IP/auth/realms/myrealm/protocol/openid-connect/userinfo'

```
I would be glad if someone could help me with this issue :).

**Comment by surfer190** [comment]
If you go to:

http://KEYCLOAK-IP/auth/realms/{realm}/.well-known/openid-configuration

All the endpoints are given. I'm testing this now though and will get back to you.

**Comment by surfer190** [comment]
It looks like you need to set the following as well for the `RS256` algo:

    OIDC_RP_IDP_SIGN_KEY = 'XXX'

**Comment by surfer190** [comment]
After debugging I noticed the error keycloak gives is indeed a `400 Bad request` with the json:

`{"error":"invalid_grant","error_description":"Code not valid"}`

Also while debugging I found the first time the `get_token` method is called, it is `200 OK`.
It however makes a call the second time that fails.
Django returns a `302` on the first one and a `500` on the second.

Not sure why it makes 2 requests in such a short space of time.

**Comment by surfer190** [comment]
Ah, you need to set your login and logout urls:

```
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
```

If they are set as:

```
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
```

It will duplicate the callback for the login - causing the failure.

**Comment by cburmeister** [comment]
We're running into something similar while using Hydra as an OAuth provider.

In our scenario -- somewhere during the callback you can see that this library is requesting the token endpoint a second time which causes the provider to return a 400:
```
hydra-86bc4bd495-g594p hydra {"level":"info","method":"POST","msg":"started handling request","remote":"10.22.10.132:36366","request":"/oauth2/token","time":"2019-11-21T21:24:29Z"}
hydra-86bc4bd495-g594p hydra {"level":"info","measure#hydra/public: https://accounts.staging.discogs.com/.latency":380633105,"method":"POST","msg":"completed handling request","remote":"10.22.10.132:36366","request":"/oauth2/token","status":200,"text_status":"OK","time":"2019-11-21T21:24:30Z","took":380633105}
[...]
hydra-86bc4bd495-g594p hydra {"level":"info","method":"GET","msg":"started handling request","remote":"10.22.10.132:36374","request":"/.well-known/jwks.json","time":"2019-11-21T21:24:30Z"}
hydra-86bc4bd495-g594p hydra {"level":"info","measure#hydra/public: https://accounts.staging.discogs.com/.latency":11210835,"method":"GET","msg":"completed handling request","remote":"10.22.10.132:36374","request":"/.well-known/jwks.json","status":200,"text_status":"OK","time":"2019-11-21T21:24:30Z","took":11210835}
[...]
hydra-86bc4bd495-g594p hydra {"level":"info","method":"POST","msg":"started handling request","remote":"10.22.10.132:37056","request":"/oauth2/token","time":"2019-11-21T21:25:00Z"}
hydra-86bc4bd495-g594p hydra {"description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client","error":"invalid_grant","hint":"The authorization code has already been used.","level":"error","msg":"An error occurred","time":"2019-11-21T21:25:00Z"}
hydra-86bc4bd495-g594p hydra {"level":"debug","msg":"Stack trace: \ngithub.com/ory/fosite/handler/oauth2.(*AuthorizeExplicitGrantHandler).HandleTokenEndpointRequest\n\t/go/pkg/mod/github.com/ory/fosite@v0.30.0/handler/oauth2/flow_authorize_code_token.go:70\ngithub.com/ory/fosite.(*Fosite).NewAccessRequest\n\t/go/pkg/mod/github.com/ory/fosite@v0.30.0/access_request_handler.go:89\ngithub.com/ory/hydra/oauth2.(*Handler).TokenHandler\n\t/go/src/github.com/ory/hydra/oauth2/handler.go:548\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/julienschmidt/httprouter.(*Router).Handler.func1\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334\ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/ory/hydra/x.RejectInsecureRequests.func1\n\t/go/src/github.com/ory/hydra/x/tls_termination.go:55\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/metricsx.(*Service).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.73/metricsx/middleware.go:261\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/hydra/metrics/prometheus.(*MetricsManager).ServeHTTP\n\t/go/src/github.com/ory/hydra/metrics/prometheus/middleware.go:26\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP\n\t/go/pkg/mod/github.com/meatballhat/negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:136\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","time":"2019-11-21T21:25:00Z"}
hydra-86bc4bd495-g594p hydra {"level":"info","measure#hydra/public: https://accounts.staging.discogs.com/.latency":165936318,"method":"POST","msg":"completed handling request","remote":"10.22.10.132:37056","request":"/oauth2/token","status":400,"text_status":"Bad Request","time":"2019-11-21T21:25:00Z","took":165936318}
```

It's obvious why the second request to the endpoint failed, the authorization code has already been used to obtain a token... I just can't determine why the library isn't returning a 302 during the callback is it should but instead attempting to request the token endpoint a second time.

**Comment by nedy13** [comment]
I only want to tell you about our observations. I don't know how django handles the stuff, but don't think it is a django-oic issue.

We are also using a OIC implementation in Java. We observed also this problem. Seems a keycloak issue. Our relogin mechanism, when the webclient session is expired, is using the same access_token. The access_token is only valid for 5 minutes by default in Keycloak. So I implemented a mechanism that a new access_token is requested from the refresh_token.
For testing we reduced the Access token lifetime to 1 minute.

The procedure is as follows:
1. Request access token and store access token and refresh token
2. after one minute our webclient session is expired and also the access token
3. We request a new access token with help of refresh token
4. Keycloak returns HTTP-400 "error":"invalid_grant","error_description":"Code not valid"

When I set "Access Token Lifespan" to 2 minutes and make the described procedure again, then everything is ok. Seems Keycloak doesn't like two requests within 1-2 minutes for the same access_token / refresh_token.

**Comment by JustFerry** [comment]
Did you end up finding a solution for this?

**Comment by yasminetta1994** [comment]
I have the same problem and it doesn't work for me!
If anyone found a solution please help me.

**Comment by kosme10** [comment]
> I have the same problem and it doesn't work for me!
> If anyone found a solution please help me.

Changing the "Login action timeout" value to a higher number worked for me.

**Comment by fronbasal** [comment]
I have the same problem. I tried increasing the timeout (1h) as @kosme10 suggested and both variables are set, as @surfer190 suggested. I will attempt to dive deeper.

**Comment by strus38** [comment]
Hello
I am having the same issue with Keycloak ... trying to integrate this with NetBox... any hints please? (note: those IPs are not exposed to internet, so no risks for the secrets)
```
OIDC_RP_CLIENT_ID: "netbox"
OIDC_RP_CLIENT_SECRET: "65345fb6-e4fd-4913-a752-a275a7a87d98" 
OIDC_OP_AUTHORIZATION_ENDPOINT: "https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/auth" 
OIDC_OP_TOKEN_ENDPOINT: "https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT: "https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/userinfo"
```
I get this error:
```
<class 'django.core.exceptions.ImproperlyConfigured'>

Setting OIDC_OP_TOKEN_ENDPOINT not found

Python version: 3.7.9
NetBox version: 2.9.7
```
Keycloak .well-known file:
```
{"issuer":"https://keycloak.home.lab/auth/realms/master","authorization_endpoint":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/auth","token_endpoint":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/token","token_introspection_endpoint":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/userinfo","end_session_endpoint":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/logout","jwks_uri":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/certs","check_session_iframe":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"id_token_encryption_alg_values_supported":["RSA-OAEP","RSA1_5"],"id_token_encryption_enc_values_supported":["A128GCM","A128CBC-HS256"],"userinfo_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"response_modes_supported":["query","fragment","form_post"],"registration_endpoint":"https://keycloak.home.lab/auth/realms/master/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"claims_supported":["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email","acr"],"claim_types_supported":["normal"],"claims_parameter_supported":false,"scopes_supported":["openid","openid","microprofile-jwt","web-origins","roles","phone","address","email","profile","offline_access"],"request_parameter_supported":true,"request_uri_parameter_supported":true,"code_challenge_methods_supported":["plain","S256"],"tls_client_certificate_bound_access_tokens":true,"introspection_endpoint":"https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/token/introspect"}
```
Also I put those value in Keycloak:
Login action timeout: 10mn
Access Token Lifespan: 1mn

If someone has an idea, it would be great!
Thanks!

**Comment by airen29** [comment]
I've got a similar problem. 
Error was: `Keycloak returns HTTP-400 "error":"invalid_grant","error_description":"Code not valid"` 
I've solved this problem by setting `Access Token Lifespan` to higher numbers.

Then I've encoutered the problem, that Keycloak endpoint `/token` was on first attempt returning `200 OK` but didn't respond with `access_token`. On second attempt I've got `400` HTTP error. I've solved this problem thanks to adding `*` into `web origin` in `Keycloak` settings.

I hope this answer helps someone.

**Comment by mariocozta** [comment]
_I know this is a Django repo if I could I would like to leave here my solution for those who, like me, got here not searching necessarily for django. If you feel like it does not fit please delete the comment._ 

So in my case I am using a React app and I was calling the token endpoint inside a use effect, and because the **component was rendering twice** (because yey react) it was sending two requests to keycloak. It seems that when keycloak recieves two requests with the same authorization code it invalidates that token session. Although the token itself is still valid, keycloak wont validate it, but you can use it with an api that has keycloaks public key and it will be valid. Probably wont be able to refresh it though (did not test) 

So on first request I got 200 and a token and on the second a 400. Easiest way to fix this in react is to just navigate to another page on the useEffect[] and so It wont render the callback page twice. 

so recaping, for anyone out there getting this, just check if you are not calling /token twice with the same authorization token.
