### ISSUE TITLE
Improve JWT signature verification

### ISSUE THREAD

**Issue by johngian** [mozilla/mozilla-django-oidc#33]

**Comment by johngian** [comment]
Here are some suggestions about this issue:

* Instead of decoding the JWT token in order to verify it implicitly we should use JWS instead to verify it explicitly
* Investigate if ``python-jose`` [1] is a better fit instead of ``PyJWT``.
  * ``PyJWT`` doesn't have a documented API for JWS
  *  JWS API implementation in ``python-jose`` looks more friendly to what we are trying to achieve
* Support ``RSxxx`` and ``ECxxx`` algorithms
  * This can be tackled in another issue
  * We should at least document what we are supporting

[1]  https://github.com/mpdavis/python-jose/

**Comment by akatsoulas** [comment]
This is now merged.
