### ISSUE TITLE
ImportError: Removal of "six" from django.utils in Django version 3.0

### ISSUE THREAD

**Issue by mjstealey** [mozilla/mozilla-django-oidc#333]
Reference: https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

The `from django.utils import six` import in [auth.py](https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/auth.py#L18) will fail under Django 3.0

> from django.utils import six
> ImportError: cannot import name 'six'

**Comment by willkg** [comment]
Pretty sure this is fixed by #322.

**Comment by mjstealey** [comment]
> Pretty sure this is fixed by #322.

Ah, yes, you are correct!
Assuming it'll get released once the failing checks are resolved.
Will self resolve in the meantime.

Closing, and thanks for the quick response!

**Comment by jaap3** [comment]
@mjstealey The failing check seemed to be caused by a network issue at Travis at the time. I've been trying to get someone to rerun the checks and do a full review. I'm hoping that after the holiday period there will be someone that has some time available.
