### ISSUE TITLE
ImportError: cannot import name 'six' - django.utils.six removed from Django 3.0

### ISSUE THREAD

**Issue by david-steffen** [mozilla/mozilla-django-oidc#334]
First off, I'd like to say thanks for your time in creating this library.

The two options are importing six directly or just removing it and supporting python3 only. Is there any reason to continue using six for compatibility?

I'm happy to create a pull request for either option, just let me know which is preferred.

Thanks

**Comment by johngian** [comment]
Since we still use python 2x i suggest we just add `six` in dependencies and import directly the library as suggested in Django 3.0 changelog.

**Comment by johngian** [comment]
Already fixed in master
