### ISSUE TITLE
How to view or access the token JSON?

### ISSUE THREAD

**Issue by surfer190** [mozilla/mozilla-django-oidc#346]
How do you get access to attributes on the client scope or view the entire access token payload from a view?

**Comment by surfer190** [comment]
I enabled storing the id token in the session:

`OIDC_STORE_ID_TOKEN = True`

and then used the following code:

```
        auth_backend = OIDCAuthenticationBackend()
        id_token = self.request.session.get('oidc_id_token')   
        payload = auth_backend.verify_token(token=id_token)
```

To get the payload.
There is another issue in how do you refresh the token when new client scopes are added?

**Comment by akatsoulas** [comment]
Hi @surfer190 is this issue still relevant? Could you maybe describe in more detail what are you trying to achieve?

**Comment by surfer190** [comment]
Hi,I was looking to view the contents of the id and access JWT's.
I achieved this with the code above.
I think a simple browser refresh or login/logout refreshed the client scopes.

Closing the issue.
