### ISSUE TITLE
Django CSRF token invalid after session refresh

### ISSUE THREAD

**Issue by bsteverink** [mozilla/mozilla-django-oidc#348]
Please point me in the right direction if this is not the proper place to post this issue. 

I have implemented mozilla-django-oidc 1.2.3 in several of my projects. However when the user takes more time that the session expiration time to fill in a form, the csrf token that has been added to the form at page load time is invalidated (a new token is created by Django on session refresh if I understand correctly). 

Should the mozilla-django-oidc library provide a mechanism to keep the csrf token in sync (would involve some serious hacking I would say), or am I missing something?

Any pointers/help is appreciated.

**Comment by drwonky** [comment]
The csrf token is not generated or manipulated by mozilla_django_oidc.  What's happening is that you have the middleware enabled and the session is being reauthed after 15 minutes.  The middleware only runs on GET method requests, so a form submission via POST should still be valid.  I suggest you record the network interaction in your browser, because I suspect your problem isn't the middleware if POST is affected.

**Comment by crgwbr** [comment]
@drwonky @bsteverink I've seen the same issue in my projects. For me at least, it happens as a result of multiple-tabs being open. 

1. Tab A: Load Form with CSRF token embedded in a form field
2. Tab B: Load some page
3. Wait a few minutes.
4. Tab B: Reload page. This triggers the session refresh. The `csrftoken` cookie is changed in the response from the `OIDCAuthenticationCallbackView` view.
5. Tab A: Submit form. Get _Forbidden (403) CSRF verification failed_ error.

I'm still working on figuring out why exactly `OIDCAuthenticationCallbackView` cycles the CSRF token cookie. Regardless, it seems like that's the problem we need a solution form.

**Comment by bsteverink** [comment]
@crgwbr I think you are spot on in the update. This would solve my issue. The django login method generates a new CSRF token invalidating the one sent with the original POST request.
