### ISSUE TITLE
Authorization - how map claims to Django groups 

### ISSUE THREAD

**Issue by luzik** [mozilla/mozilla-django-oidc#351]
I have to assign Django permissions based on provided claims - it is possible with mozilla-django-oidc ?

**Comment by OmenApps** [comment]
Sure. You can specify which scopes from the provider to use, and how you want to use them.

Take a look at these sections of the documentation:

- https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#advanced-claim-verification
- https://mozilla-django-oidc.readthedocs.io/en/stable/settings.html#OIDC_RP_SCOPES
- https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#changing-how-django-users-are-created
