### ISSUE TITLE
keycloak Multi tenancy SaaS Like Isolation with django rest api

### ISSUE THREAD

**Issue by rkpip3** [mozilla/mozilla-django-oidc#361]
How to implement keycloak Multi tenancy SaaS Like Isolation with django rest api.

1. signup. A Company should be created.
2. create other users in the same company
3. see a list of users from the same company.

**Comment by akatsoulas** [comment]
Hi @rkpip3, it looks like this issue is not related to the OIDC lib thus I am closing it. Thank you for taking the time submitting it
