### ISSUE TITLE
Configure settings as class variables on the middleware class

### ISSUE THREAD

**Issue by dreynolds** [mozilla/mozilla-django-oidc#369]
In most other classes (views, authentication backend) the settings are set as instance variables on the class using `get_settings`/`import_from_settings`. This makes overriding them a lot easier - you can just override the `__init__` method of the class and set them directly.

It would be nice if we could do this same thing in the middleware class. At present there are multiple calls to `self.get_settings` in the `process_request` method meaning one would have to override the whole method in order to change where the openid settings come from.

Does this seem like a feature that would be useful to people other than me?

**Comment by jwhitlock** [comment]
I also prefer the settings pattern that reads directly from settings in the ``__init__.py`` method, like [UpdateCacheMiddleware](https://github.com/django/django/blob/4d973f593932285cd2f765400d915305d8e7333a/django/middleware/cache.py#L66-L73) from Django:

```
    def __init__(self, get_response=None):
        self._get_response_none_deprecation(get_response)
        self.cache_timeout = settings.CACHE_MIDDLEWARE_SECONDS
        self.page_timeout = None
        self.key_prefix = settings.CACHE_MIDDLEWARE_KEY_PREFIX
        self.cache_alias = settings.CACHE_MIDDLEWARE_ALIAS
        self.cache = caches[self.cache_alias]
        self.get_response = get_response
```

I'm curious why ``import_from_settings`` was seen as necessary. @akatsoulas, any idea what the design process was around https://github.com/mozilla/mozilla-django-oidc/pull/10? If you don't, that's OK - I can barely remember last week, much less 2016.

**Comment by willkg** [comment]
I bet this is my fault. A long time ago, @peterbe and I had different implementations of the SessionRefresh middleware and then I think I merged those into this project when we decided this was the way to go and that's probably why it's got different way of doing things.

**Comment by peterbe** [comment]
Could the excuse/explanation be that we made it like that because we wanted to make it easier to write some unit tests?
(disclaimer; I haven't even looked at the source code of this in years as none of my current projects are using it)

**Comment by dreynolds** [comment]
If I made a PR updating the `SessionRefresh` middleware class to work in the way described would that be accepted?

**Comment by akatsoulas** [comment]
> I'm curious why `import_from_settings` was seen as necessary. @akatsoulas, any idea what the design process was around #10? If you don't, that's OK - I can barely remember last week, much less 2016.

As far as I recall it was a way to import settings without calling the django `settings` module. We also wanted a single method to handle any kind of configuration (if there was ever the need). Also the reason for writing this lib back then was the deprecation of persona and we needed something to work with the OIDC provider without having to code each project separately. Because of that the Django lib for BrowserID was used as inspiration and If I am not mistaken this (or a similar) helper was in there and seemed like a good idea.

**Comment by akatsoulas** [comment]
@dreynolds You should be able to override the `get_settings` method to pass any settings you may want in the `process_request` without the need to override the later only for settings. Is this a viable option for your use case?

**Comment by dreynolds** [comment]
> @dreynolds You should be able to override the `get_settings` method to pass any settings you may want in the `process_request` without the need to override the later only for settings. Is this a viable option for your use case?

It is.. but it would be nicer if all of the classes worked in the same way

**Comment by akatsoulas** [comment]
> If I made a PR updating the `SessionRefresh` middleware class to work in the way described would that be accepted?

It would be more than welcome :)

**Comment by dreynolds** [comment]
Done: https://github.com/mozilla/mozilla-django-oidc/pull/372 

Please let me know if there's anything I need to add. I'm not really sure why those Travis tests failed - from the log output it doesn't look like anything went wrong?

**Comment by akatsoulas** [comment]
Thanks @dreynolds for this PR and apologies it took a bit longer. I am closing this issue and I will follow up with a release towards the end of the week.
