### ISSUE TITLE
Deprecation warnings with Django 3.1

### ISSUE THREAD

**Issue by jannh** [mozilla/mozilla-django-oidc#370]
In my unittests, I discovered some deprecation warnings:

.../python3.8/site-packages/mozilla_django_oidc/urls.py:21: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
  url(r'^callback/$', OIDCCallbackClass.as_view(),

This should be easy to fix for all Django versions 2.0 and greater (replace by path syntax). I can provide a PR, do you still support Django 1.11 and Python 2.7 or can this just be replaced?

.../python3.8/site-packages/mozilla_django_oidc/views.py:130: RemovedInDjango40Warning: django.utils.http.is_safe_url() is deprecated in favor of url_has_allowed_host_and_scheme().
  is_safe = is_safe_url(**kwargs)

This is only a rename and works for all version of Django >= 3.0 - maybe, this can be fixed later, when Django 2.2 is EOL.

**Comment by akatsoulas** [comment]
@jannh Now that Django 1.11 is no longer supported I think it's OK to remove support for it in the future versions of the lib (along with Python 2.7). Please feel free to open a PR for this if you would like. Django 2.2 won't be reaching its EOL for more than 1,5 years.

**Comment by akatsoulas** [comment]
Fixed in #371, merged in #403
