### ISSUE TITLE
scopes are not encoded correctly

### ISSUE THREAD

**Issue by sannies** [mozilla/mozilla-django-oidc#373]
Current code redirects to provider/login?scopes=scope1+scope2+scope3 but that is not correct (most providers understand it nonetheless). AWS Cognito doesn't support it and requires cognitohost/login?scopes=scope1%20scope2%20scope3.

**Comment by sannies** [comment]
https://github.com/mozilla/mozilla-django-oidc/pull/374

**Comment by akatsoulas** [comment]
Fixed in #404. Thanks @sannies for reporting this
