### ISSUE TITLE
Use preferred_username from claim for newly created username

### ISSUE THREAD

**Issue by 2chg** [mozilla/mozilla-django-oidc#396]
When creating a local user from an OIDC authentication, the username will always be derived from the `email` field. (The method configured via `OIDC_USERNAME_ALGO` only gets the email address)

Despite the fact that using the `preferred_username` field would be more naturally, there seems to be no simple way to change the chosen field. (Or I simply can't find it.)

Maybe an optional settings parameter like `OIDC_USERNAME_ATTRIBUTE` (to maintain backwards compatibility defaulted to `email`) could be a solution?

**Comment by akatsoulas** [comment]
Hi @2chg! You can override the `get_username` method [0] to customize the username. Would that work for your use case?

**Comment by akatsoulas** [comment]
I am closing this issue for now. Please re-open if the proposed solution does not work

**Comment by james-mchugh** [comment]
Hi. This works for us, but I'm curious why the email was used over the `preferred_username` claim from the start? Is there any reason we shouldn't use the `preferred_username` claim here?
