### ISSUE TITLE
supprting GET for logout should be behind a setting

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#405]
Issue #126 intentionally switched logout to be POST-only, but PR #402 switches it so that either GET or POST is allowed. Having it support GET before was raised in a security review which is one of the reasons we changed it. I really don't want to support GET as a logout possibility.

If we must support both, I'd appreciate us putting GET support behind a setting.

**Comment by johngian** [comment]
Hey @willkg thanks for the feedback. I didn't remember the security aspect, only the discussion about the semantics of get/post on logout. Also i think the OIDC spec uses GET on `/logout` so I thought it would be ok to allow the same endoint. I am happy to put it behind a config entry to opt in instead or even completely removing it.

@akatsoulas thoughts?

**Comment by willkg** [comment]
Where's that in the OIDC spec? Does it require the GET path to have a CSRF or something similar?

**Comment by willkg** [comment]
I found the security review for mozilla-django-oidc and I misremembered. I fixed a next link issue for that. It didn't include anything about GET vs. POST for logouts. Sorry about that!

**Comment by akatsoulas** [comment]
I just skimmed through the [RP initiated logout documentation](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) and it looks like RPs can send both. That said, I also missed the context that @willkg provided. Let's default to POST and have a setting for the GET part

**Comment by johngian** [comment]
This is what I found: https://openid.net/specs/openid-connect-frontchannel-1_0.html, not really part of the core spec.
```
 This specification defines a logout mechanism that uses front-channel communication via the User Agent between the OP and RPs being logged out that does not need an OpenID Provider iframe on Relying Party pages, as OpenID Connect Session Management 1.0 [OpenID.Session] does. Other protocols have used HTTP GETs to RP URLs that clear login state to achieve this; this specification does the same thing. 
``` 

That said I don't have any strong opinion about that.

**Comment by akatsoulas** [comment]
Closing after #406
