### ISSUE TITLE
update setup.py classifiers regarding support

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#407]
The classifiers in setup.py need to be updated after pr #403:

https://github.com/mozilla/mozilla-django-oidc/blob/821de3d54e299f75ba3d7d2d3d4846a3ed7cd836/setup.py#L57-L78

I don't know if we talk about supported Django and Python versions elsewhere, but they should get updated to if they were missed.

**Comment by akatsoulas** [comment]
Thanks @willkg! Fixed in #408
