### ISSUE TITLE
Redirect URI incorrect when running Daphne

### ISSUE THREAD

**Issue by flabbyThoroughbred** [mozilla/mozilla-django-oidc#409]
I'm running my Okta authenticated django app on Daphne and encountering into an issue where the redirect URI is coming up as http instead of https. As a result I get a Bad Request error when loading my okta login screen.

Since I'm behind an application load balancer that's handling all my https traffic, I don't have Daphne configured to run ssl. It's a pretty bare-bones configuration: just passing a port and host. 

I think this might be the reason it's rendering the redirect as http. I've run the app with uwsgi and I haven't had this problem.

Is there some way to specify an explicit redirect URI in the settings or otherwise redirect to https? My only other thought would be to subclass OIDCAuthenticationRequestView and have it force to https but that seems rather unnecessary.

**Comment by willkg** [comment]
Did you set `LOGIN_REDIRECT_URL`?

https://mozilla-django-oidc.readthedocs.io/en/stable/settings.html#LOGIN_REDIRECT_URL

**Comment by flabbyThoroughbred** [comment]
I have **LOGIN_REDIRECT_URL** correctly set to go to my main page when login is successful.
I'm referring to the redirect_uri that would look like **https://{my site}/oidc/callback** 
This is the same redirect that I set up on my Okta app configuration.

The redirect is dynamically built in the authenticate method of **OIDCAuthenticationBackend**. 
The **https://{my site}** portion is provided by the request itself and I think the request is defaulting the protocol to http. I can only provide a custom callback pattern with with **OIDC_AUTHENTICATION_CALLBACK_URL** but I'm (as far as I'm aware) unable to provide an explicit redirect uri. I'm currently trying to force all requests to https right now but I still haven't gotten it to work correctly.

**Comment by flabbyThoroughbred** [comment]
Turns out I didn't need to bother overriding anything or otherwise break the module. 
I just passed **SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')**
And all is well!

That being said, being able to specify oidc login redirect (not the redirect that would happen after successful authentication) may still be useful.
