### ISSUE TITLE
IFrame and OIDC authentication

### ISSUE THREAD

**Issue by leuat** [mozilla/mozilla-django-oidc#440]
Hi there!

I'm using mozilla-django-oidc to authenticate users across a platform, which is working just fine. However, my page is supposed to be integrated into a larger framework using iframes - and then oidc authentication fails spectacularly (nothing is rendered, just getting redirected back to the main page). 

Any ideas / settings to allow  authentication from iframes?

**Comment by ingGhost** [comment]
> Hi there!
> 
> I'm using mozilla-django-oidc to authenticate users across a platform, which is working just fine. However, my page is supposed to be integrated into a larger framework using iframes - and then oidc authentication fails spectacularly (nothing is rendered, just getting redirected back to the main page).
> 
> Any ideas / settings to allow authentication from iframes?

hy can u give me example how to use SSO for cross platform?
