### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by GliderGeek** [mozilla/mozilla-django-oidc#455]
From the current [ tox file](https://github.com/mozilla/mozilla-django-oidc/blob/master/tox.ini) i conclude that 3.2 is the latest django version which is supported by this library. Is support for django 4 something that you are willing to add?

**Comment by jaap3** [comment]
I don't think anybody is opposed to adding Django 4 support. It's just a matter of somebody doing the required work (i.e. changing the tox, circleci and github workflows to also run the test suite on Django 4, and fixing any potential issues). (This could be you perhaps?).

Once that is done, it should still be reviewed and merged. This last step seems to be a challenge currently. There are multiple Pull requests that have yet to be reviewed. It's almost af is this project has been abandonned by Mozilla (is that right @akatsoulas?).

**Comment by akatsoulas** [comment]
Truth is that the project needs a bit more love and maintenance. Hopefully though this is about to change. I am picking up this issue to add Django 4 support within next week.

**Comment by akatsoulas** [comment]
A new version has been released to PyPI which adds support for Django 4

**Comment by jaap3** [comment]
@akatsoulas could you add the release to GitHub as well (https://github.com/mozilla/mozilla-django-oidc/releases)?
