### ISSUE TITLE
Release request: SessionRefresh should respect the OIDC_AUTH_REQUEST_EXTRA_PARAMS setting

### ISSUE THREAD

**Issue by jtrivett** [mozilla/mozilla-django-oidc#466]
In v2.0.0, I noticed that the `SessionRefresh.process_request` method is not including the value of the  `OIDC_AUTH_REQUEST_EXTRA_PARAMS` setting when it generates the request URL to refresh the OIDC token.

As I began troubleshooting this and determining a workaround for the code at-fault, I found that a fix was committed in Jan 2022 (https://github.com/mozilla/mozilla-django-oidc/commit/d42bada03715ecee00bb0b27ce17283ce51255ac), but has yet to be released.

Are there any existing plans to publish a new release in the near future? If not, may I request that a release be published to include this particular fix?

**Comment by akatsoulas** [comment]
A new version which includes this commit has been released to PyPI

**Comment by jtrivett** [comment]
Thanks for the update! Will look forward to the release notes for 3.0.0 😃
