### ISSUE TITLE
401 Client Error 

### ISSUE THREAD

**Issue by lucaromagnoli** [mozilla/mozilla-django-oidc#481]
Hi,

I'm trying to integrate Django and Keycloack using `mozilla-django-oidc`, but unfortunately I'm not having much success.

I created a docker compose that runs Keycloack / KeycloackDB / Django app, like the following

`docker-compose.yaml`

```docker
version: '3'

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local-keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - "start-dev"
    networks:
      - local-keycloak
    volumes:
    - .local/keycloak/:/opt/keycloak/data

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - keycloak
    volumes:
      - .:/app
    networks:
      - local-keycloak

networks:
  local-keycloak:

```

I setup my Django project as described in https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#quick-start

`settings.py`
```
....
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "mozilla_django_oidc.auth.OIDCAuthenticationBackend",
)

BASE_URL = "http://localhost:8080"
KEYCLOACK_IP = "http://192.168.192.3:8080"


OIDC_RP_SIGN_ALGO = "RS256"
OIDC_OP_JWKS_ENDPOINT = f"{KEYCLOACK_IP}/realms/demo/protocol/openid-connect/certs"

OIDC_RP_CLIENT_ID = os.environ['OIDC_RP_CLIENT_ID']
OIDC_RP_CLIENT_SECRET = os.environ['OIDC_RP_CLIENT_SECRET']

OIDC_OP_AUTHORIZATION_ENDPOINT = f"{BASE_URL}/realms/demo/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = f"{KEYCLOACK_IP}/realms/demo/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = f"{KEYCLOACK_IP}/realms/demo/protocol/openid-connect/userinfo"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
```

`views.py`

```
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.template import loader


def index(request):
    template = loader.get_template('index.html')

    return HttpResponse(template.render({}, request))
```

`index.html`

```HTML
{% if user.is_authenticated %}
  <p>Current user: {{ user.email }}</p>
  <form action="{% url 'oidc_logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="logout">
  </form>
{% else %}
  <a href="{% url 'oidc_authentication_init' %}">Login</a>
{% endif %}

```

In the running Keycloack instance I created a new realm

<img width="1503" alt="Screenshot 2022-12-15 at 14 10 07" src="https://user-images.githubusercontent.com/38782977/207882594-44b4e17e-aba2-4964-99cf-76fe104fb10a.png">

And also a new client
<img width="1286" alt="Screenshot 2022-12-15 at 14 13 27" src="https://user-images.githubusercontent.com/38782977/207883209-e632121f-7669-4b76-a062-63bce038b67b.png">

Now when I try to authenticate, I get correctly redirected to Keycloack. After entering the credentials I am always getting this error

`401 Client Error: Unauthorized for url: http://192.168.224.3:8080/realms/demo/protocol/openid-connect/userinfo`

I should also mention that I tried both OIDC_OP_JWKS_ENDPOINT and OIDC_RP_IDP_SIGN_KEY and I'm getting exactly the same error (401). Also please note that for some of the settings I had to use the physical IP of the docker container in order for Keycloack to provide a token.

Any help would be greatly appreciated as right now I'm totally blocked. 
Please let me know if you need more info from me.

Cheers

**Comment by lucaromagnoli** [comment]
For anyone who may have come across this issue.

The problem was caused by the fact that I was trying to access Keycloack via `localhost:8080` or the docker network IPv4. The solution is to point django to `http://keycloack:8080`

**Comment by sagarguptay2j** [comment]
I'm running into exact same issue can you explain your solution in detailed steps

my docker-compose:
version: "3.7"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=squadrun
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ~/.siq/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    expose:
      - 6379
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=squadrun worker -Q voice_make_ivr_india_queue,voice_send_email_india_queue,voice_send_email_india_upstox_queue,voice_send_sms_india_queue,voice_workflow_india_queue,celery_voice,ivr_queue,voice_analytics_and_metrics_queue,voice_fsm_india_queue,dnd_queue,voice_bulk_sync,voice_dnd_and_compliance_actions_queue,voice_notifications_queue,voice_make_ivr_india_queue,voice_send_email_india_queue,voice_send_email_india_upstox_queue,voice_send_sms_india_queue,voice_sync_ivr_details_india_queue,voice_workflow_india_queue,voice_sync_sms_details_india_queue,voice_send_sms_india_upstox_queue,voice_dnd_and_compliance_actions_upstox_queue,voice_imports_queue --concurrency=3 --without-heartbeat --without-gossip -n celery.%%h --loglevel=INFO
    container_name: celery
    working_dir: /home/docker/code
    volumes:
      - .:/home/docker/code
    depends_on:
      - db
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -Wignore manage.py runserver 0.0.0.0:8001
    container_name: django_web3
    volumes:
      - .:/home/docker/code
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    command: start-dev
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

settings.py:
OIDC_RP_CLIENT_ID = "voice-dashboard"
OIDC_RP_CLIENT_SECRET = "c2gpXYAZ30JJJ1lHt06MoXLGklo3iPLE"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_OP_JWKS_ENDPOINT = "http://host.docker.internal:8080/realms/SquadStack/protocol/openid-connect/certs"
OIDC_OP_AUTHORIZATION_ENDPOINT = "http://localhost:8080/realms/SquadStack/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "http://host.docker.internal:8080/realms/SquadStack/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "http://host.docker.internal:8080/realms/SquadStack/protocol/openid-connect/userinfo"
LOGIN_REDIRECT_URL = "http://0.0.0.0:8001/voice/dashboard/index/"
LOGOUT_REDIRECT_URL = "http://0.0.0.0:8001/voice/dashboard/index/"
