### ISSUE TITLE
document how to deal with custom user model (email-only)

### ISSUE THREAD

**Issue by wimfeijen** [mozilla/mozilla-django-oidc#482]
Hi,

As far as I can see, OIDCAuthenticationBackend.create_user will fail if we are dealing with a user with no username.

We should probably document how to deal with a custom user model. 

For example, I am dealing with a usermodel with no username and only email. What I did was overwrite create_user in MyOIDCBackend.

**Comment by akatsoulas** [comment]
Thank you for filing this issue. It should be fixed via #508. Please reopen if this is not the case.
