### ISSUE TITLE
Logout user from OP in the logout view.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozilla-django-oidc#66]

**Comment by willkg** [comment]
Is this covered here already?:

https://github.com/mozilla/mozilla-django-oidc/blob/8d096dc0d1709e87fda80ce896a8a097d8ee3a03/mozilla_django_oidc/views.py#L122

**Comment by akatsoulas** [comment]
Yes! Probably forgot to close the issue. Thanks!
