### ISSUE TITLE
Make auth0 middleware compatible with Django>1.10

### ISSUE THREAD

**Issue by johngian** [mozilla/mozilla-django-oidc#90]
Starting from version 1.10, Django introduced a new style for middleware classes.
https://docs.djangoproject.com/en/1.11/releases/1.10/#new-style-middleware

At the moment ``contrib.auth0.middleware`` is not compatible nor tested. We should make sure to adapt it to these changes.

**Comment by willkg** [comment]
I'll work on this today.
