### ISSUE TITLE
User username field shouldn't get a bytes value

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#91]
The Django username field should get a unicode value in Python 2 and a string value in Python 3.

However, it's getting the output of `default_username_algo` which generates a string in Python 2 (which is fine since there are no non-ascii characters in it) and a bytes in Python 3 (which is probably not fine).

Further, the signature for username generation functions is "weird" in the sense that it takes a string/bytes as an argument and returns a string/bytes--but it operates on an email address and returns a username. That feels weird.

This issue covers fixing this part of the API.

**Comment by willkg** [comment]
I claim we should do the following:

1. change the signature for the username generation algorithm so that it takes a string/unicode (it's an email address, so if it's anything else, that's weird) and returns a string/unicode
2. fix the `default_username_algo` accordingly

Does that make sense? If so, I can throw together a fix today.

I can't tell if this is related to #89 since there's no traceback, so I have no idea where that error is occurring.

**Comment by akatsoulas** [comment]
@willkg it totally does make sense!
