### ISSUE TITLE
Support prompt parameter none instead of the delegation endpoint

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/mozilla-django-oidc#94]
prompt=none is the OIDC standard and is now supported by auth0:
https://auth0.com/docs/api-auth/tutorials/silent-authentication

Sample (Lua):
https://github.com/pingidentity/lua-resty-openidc/commit/2d21cb521f5edebb76af27bfb1f7a44264d8372e

In other words, instead of calling the delegation endpoint (auth0 specific) we pass a prompt=none parameter to the authorization endpoint, which will return the current id_token (just like delegation endpoint) without prompting the user

**Comment by gdestuynder** [comment]
Same for Flask-pyoidc: https://github.com/zamzterz/Flask-pyoidc/pull/17

**Comment by willkg** [comment]
I was going to work on this today. Pretty sure it's straight forward. The link to the flask equivalent helps.

**Comment by peterbe** [comment]
@gdestuynder Pardon my ignorance but back in the day when we used `/delegation` instead to renew the ID token we were able to do that **from the server**. I.e. a communication between, say, airmozilla and auth0. The client would not even notice, at all, when things go well. In @willkg 's implementation in https://github.com/mozilla/mozilla-django-oidc/issues/127 he makes the **user** redirect to renew the ID token if it needs to be renewed. If all goes well, the redirect should just flash by and redirect back to where you were and all the user sees is a delay and flashing pages that zip by. 

Is there not a way to do the renewal of the ID token without forcing the user to use her browser to go there?

If the answer, to the above question, is no; can you help us how with a solution to this: https://github.com/mozilla/mozilla-django-oidc/pull/127#issuecomment-305525863

Perhaps the answer is to implement auth0 in JavaScript and do the ["silent authenticatio within a hidden iframe"](https://github.com/auth0/auth0.js#api).

**Comment by willkg** [comment]
@peterbe https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/contrib/auth0/middleware.py#L29

It was excluding AJAX-y things already.

**Comment by peterbe** [comment]
@willkg that's because the code originated from airmozilla which was/is a very server-side rendering heavy site. 

The more I think about it, single-page apps usually don't rely on cookies for auth state. You usually do an auth process, get an auth token and then pass that auth token/header or something in consecutive calls. However, we still want to have the feature that people who leave their email (e.g. leaving the company and LDAP) should be "kicked out". So there has to be some renewal since that's what we use to see if the user is still has access to the email she authenticated with. 

So normally, if I work against the GitHub API, if my token gets revoked I'll eventually get a `403 Forbidden` or something similar if I keep making calls with an old auth token.

**Comment by willkg** [comment]
I think this is out of scope for this issue because nothing is changing in this regard to support the "prompt=none" change.

I made issue #133 for covering that.

**Comment by johngian** [comment]
I don't think that this is in the scope of this issue. If we want to support single page apps we probably need to implement OpenID connect "implicit flow".

**Comment by peterbe** [comment]
OK. Let's redirect the discussion of AJAX heavy sites to #133.

My question is still this; Is it possible (without being strictly tied the vendor Auth0) to do an ID token refresh *without* forcing the user to do a redirect trip in her browser? I.e. server to server communication. (If that's done during a web request or in a cron job or message queue is irrelevant).

**Comment by willkg** [comment]
Pull #127 changes the middleware to use the authentication endpoint with prompt=none.

The single-page-app discussion is moved to #133.

That covers it for this bug--so I'm closing it out.

**Comment by gdestuynder** [comment]
Indeed, the silent authentication/prompt=none needs special handling for XHR type requests  and or posts
The delegation endpoint is auth0 specific and I suspect might be phased out eventually (thought its not on the radar so far) as auth0 is trying to standardize everything around the OIDC spec.

There is also a draft OIDC spec for session support that also works for backends - but it's still in draft and not supported anywhere yet (AFAIK)

**Comment by hmitsch** [comment]
Note to self: This was Sprint 9 scope. Delivered to PROD.
