### ISSUE TITLE
document OIDC_CREATE_USER

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#96]
When working on PR #95, one of the things that came up was whether we should also document `OIDC_CREATE_USER` in that PR.

From the comments:

> @willkg: If you have it set to False, how does the flow work? Don't you end up with a user that's authenticated, but has no corresponding Django user? What do you do at that point?

> @akatsoulas: That's a good point. A possible scenario could be the one where the authenticate method can be overridden for the use case where a developer needs just to verify an email/user data like eg in a campaign and save them (completely ignoring the Django user). That said, probably this is a hack that does not conform with the Django flow and needs some more work/thought. An idea could be to handle cases like the above at an earlier stage of the flow. @willkg @johngian thoughts?

> @willkg: I like that there's an "escape hatch", but I think any documentation for the setting should probably include some guidance on why you'd want to use it and how to use it.

This issue covers documenting that setting along with some explanation for why you might want to do that and what you need to implement to make it work well.

**Comment by pmac** [comment]
In my use case I would just like for users that aren't in the my DB but do come to the app as authenticated to be redirected to an "unauthorized" page of some sort. I want to control which people have access to my app, and so if an authentication request comes in for an email address we don't know, they should just be rejected. Perhaps we should also have a `OIDC_REJECTED_URL` setting to send them somewhere with some useful information?
